#!/usr/bin/env python3
"""Assemble labelled Safe Commit policy diagnostics from audited rollout panels.

The source panels are generated by ``export_active_catalog_rollout_visuals``
from validation-only traces. This script adds labels and trace metadata for a
supplementary mechanism figure; it does not select cases or alter the panels.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from PIL import Image


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_INPUT = ROOT / "docs" / "figures" / "safe_commit_qualitative_20260801"
DEFAULT_OUTPUT = ROOT / "docs" / "figures" / "safe_commit_policy_diagnostics_20260809"
DEFAULT_CASES = (
    "001_reshape_sn7-e6962896a645c3bb__b4p5__s0",
    "003_keep_sn7-0b7be4bef62f1296__b4p5__s0",
)
ACTION_COLORS = {
    "ACQUIRE": "#1F77B4",
    "USE_TOOL": "#9467BD",
    "COMMIT": "#2CA02C",
    "REJECT": "#7F7F7F",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input-dir", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--case", action="append", default=[])
    return parser.parse_args()


def load_image(path: Path):
    return Image.open(path).convert("RGB")


def selected_overlay(case_dir: Path, metadata: dict) -> tuple[Path, int]:
    events = metadata.get("events") or []
    acquire_steps = [int(event["step"]) for event in events if event.get("action") == "ACQUIRE"]
    step = acquire_steps[0] if acquire_steps else 0
    overlay = case_dir / f"utility_overlay_step{step:02d}.png"
    if not overlay.exists():
        overlay = case_dir / "utility_overlay_step00.png"
        step = 0
    return overlay, step


def action_text(metadata: dict) -> str:
    actions = [str(event.get("action", "REJECT")) for event in metadata.get("events") or []]
    return " -> ".join(actions) if actions else "REJECT"


def build_figure(input_dir: Path, cases: tuple[str, ...]) -> tuple[plt.Figure, list[dict]]:
    plt.rcParams.update(
        {
            "font.family": "Arial",
            "font.size": 7.5,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
            "svg.fonttype": "none",
        }
    )
    fig, axes = plt.subplots(len(cases), 4, figsize=(7.16, 1.93 * len(cases)), constrained_layout=False)
    fig.subplots_adjust(left=0.075, right=0.988, bottom=0.08, top=0.88, hspace=0.38, wspace=0.13)
    if len(cases) == 1:
        axes = axes[None, :]
    headers = ("Anchor observation", "Selected value ROI", "Belief over rollout", "Structured action trace")
    for column, header in enumerate(headers):
        axes[0, column].set_title(header, fontsize=8.2, fontweight="bold", pad=7)

    manifest_cases = []
    for row_index, case_name in enumerate(cases):
        case_dir = input_dir / case_name
        metadata = json.loads((case_dir / "metadata.json").read_text(encoding="utf-8"))
        overlay_path, selection_step = selected_overlay(case_dir, metadata)
        anchor = load_image(case_dir / "01_anchor_rgb.png")
        overlay = load_image(overlay_path)
        belief = load_image(case_dir / "belief_trajectory.png")

        for axis in axes[row_index]:
            axis.set_xticks([])
            axis.set_yticks([])
            axis.spines[:].set_visible(False)
        axes[row_index, 0].imshow(anchor)
        axes[row_index, 1].imshow(overlay)
        axes[row_index, 2].imshow(belief)
        axes[row_index, 2].set_yticks([0.12 * belief.height, 0.37 * belief.height, 0.62 * belief.height, 0.87 * belief.height])
        axes[row_index, 2].set_yticklabels(metadata["belief_rows"], fontsize=6.6)
        axes[row_index, 2].set_xticks([])

        events = metadata.get("events") or []
        actions = [str(event.get("action", "REJECT")) for event in events] or ["REJECT"]
        action_index = {name: index for index, name in enumerate(ACTION_COLORS)}
        strip = [[action_index.get(action, action_index["REJECT"]) for action in actions]]
        cmap = ListedColormap([ACTION_COLORS[name] for name in action_index])
        axes[row_index, 3].imshow(strip, aspect="auto", cmap=cmap, vmin=0, vmax=len(action_index) - 1)
        axes[row_index, 3].set_xticks(range(len(actions)), [str(index) for index in range(len(actions))], fontsize=6.5)
        axes[row_index, 3].set_xlabel("rollout step", fontsize=6.5, labelpad=1)
        for index, action in enumerate(actions):
            axes[row_index, 3].text(index, 0, action, ha="center", va="center", fontsize=5.5, color="white" if action != "REJECT" else "black", fontweight="bold")

        status = "correct" if metadata.get("terminal_correct") else "error"
        row_label = (
            f"{metadata['target_edit']} target | {metadata['predicted_edit']} output | {status}\n"
            f"cost {float(metadata.get('spent_cost') or 0.0):.2f} | value range "
            f"[{metadata['events'][selection_step]['utility_min']:.2f}, {metadata['events'][selection_step]['utility_max']:.2f}]"
        )
        axes[row_index, 0].set_ylabel(row_label, fontsize=6.5, rotation=0, ha="right", va="center", labelpad=50)
        manifest_cases.append(
            {
                "folder": case_name,
                "sample_id": metadata["sample_id"],
                "aoi_id": metadata["aoi_id"],
                "target_edit": metadata["target_edit"],
                "predicted_edit": metadata["predicted_edit"],
                "selection_step": selection_step,
                "actions": actions,
            }
        )

    fig.suptitle("Audited Safe Commit rollouts: value-aware acquisition precedes terminal writeback", fontsize=10.0, fontweight="bold")
    fig.text(
        0.5,
        0.012,
        "ROI color encodes the policy-relative candidate value at the selected acquisition step. Belief rows: KEEP, ADD, DELETE, RESHAPE.",
        ha="center",
        fontsize=6.4,
        color="#64748B",
    )
    return fig, manifest_cases


def main() -> None:
    args = parse_args()
    cases = tuple(args.case) if args.case else DEFAULT_CASES
    summary = json.loads((args.input_dir / "summary.json").read_text(encoding="utf-8"))
    if summary.get("test_assets_read") is not False:
        raise ValueError("only validation-only qualitative assets may be rendered")
    figure, cases_manifest = build_figure(args.input_dir, cases)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    stem = args.output_dir / "safe_commit_policy_diagnostics"
    figure.savefig(stem.with_suffix(".pdf"), bbox_inches="tight")
    figure.savefig(stem.with_suffix(".svg"), bbox_inches="tight")
    figure.savefig(stem.with_suffix(".png"), dpi=360, bbox_inches="tight")
    plt.close(figure)
    (args.output_dir / "source_manifest.json").write_text(
        json.dumps(
            {
                "schema_version": "safe-commit-policy-diagnostics-v1",
                "source_summary": str(args.input_dir / "summary.json"),
                "test_assets_read": False,
                "samples": cases_manifest,
                "selection_note": "Cases were selected by the pre-existing validation-only Safe Commit selection manifest; this assembler performs no ranking or reselection.",
            },
            indent=2,
        ),
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
