#!/usr/bin/env python3
"""Pair cross-fit advantage labels with one deployment adapter's hidden-state space."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from scripts.assemble_policy_relative_crossfit_features import (
    _bundle,
    _join,
    _jsonl,
    _sha256,
    _write_bundle,
)


def assemble_deployment_features(
    folds_root: Path,
    branch_root: Path,
    train_feature_root: Path,
    val_branch_root: Path,
    val_feature_root: Path,
    output_root: Path,
) -> dict[str, Any]:
    if output_root.exists():
        raise FileExistsError(f"refusing to overwrite {output_root}")
    fold_summary_path = folds_root / "summary.json"
    fold_summary = json.loads(fold_summary_path.read_text(encoding="utf-8"))
    assignments = {
        str(row["task_id"]): int(row["outer_fold"])
        for row in _jsonl(folds_root / "outer_task_assignments.jsonl")
    }
    branch_rows = []
    branch_sources = []
    for spec in sorted(fold_summary["folds"], key=lambda row: int(row["fold"])):
        fold = int(spec["fold"])
        root = branch_root / f"fold{fold}"
        rows = _jsonl(root / "traces.jsonl")
        if any(assignments.get(str(row["task_id"])) != fold for row in rows):
            raise ValueError("branch label was not generated by its assigned outer fold")
        branch_rows.extend(rows)
        branch_sources.append(
            {
                "fold": fold,
                "summary": str((root / "summary.json").resolve()),
                "summary_sha256": _sha256(root / "summary.json"),
            }
        )
    train_features, train_feature_rows, train_feature_summary = _bundle(train_feature_root)
    train_features, train_records = _join(
        train_features,
        train_feature_rows,
        branch_rows,
        split="train",
        fold=None,
        assignment=None,
    )
    for row in train_records:
        row["crossfit_fold"] = assignments[str(row["task_id"])]
    val_features, val_feature_rows, val_feature_summary = _bundle(val_feature_root)
    val_features, val_records = _join(
        val_features,
        val_feature_rows,
        _jsonl(val_branch_root / "traces.jsonl"),
        split="val",
        fold=None,
        assignment=None,
    )
    if train_features.shape[1] != val_features.shape[1]:
        raise ValueError("deployment train and validation feature dimensions differ")

    output_root.mkdir(parents=True)
    train_summary = _write_bundle(
        output_root / "train",
        train_features,
        train_records,
        split="train",
        sources=[
            {
                "deployment_feature_summary": str(
                    (train_feature_root / "summary.json").resolve()
                ),
                "deployment_feature_summary_sha256": _sha256(
                    train_feature_root / "summary.json"
                ),
                "deployment_adapter": train_feature_summary["adapter"],
                "crossfit_branch_sources": branch_sources,
            }
        ],
    )
    train_summary["crossfit_protocol"] = (
        "task-disjoint-outer-fold-labels-with-full-deployment-adapter-state"
    )
    (output_root / "train" / "summary.json").write_text(
        json.dumps(train_summary, indent=2) + "\n", encoding="utf-8"
    )
    val_summary = _write_bundle(
        output_root / "val",
        val_features,
        val_records,
        split="val",
        sources=[
            {
                "deployment_feature_summary": str(
                    (val_feature_root / "summary.json").resolve()
                ),
                "deployment_feature_summary_sha256": _sha256(
                    val_feature_root / "summary.json"
                ),
                "deployment_adapter": val_feature_summary["adapter"],
                "branch_summary": str((val_branch_root / "summary.json").resolve()),
                "branch_summary_sha256": _sha256(val_branch_root / "summary.json"),
            }
        ],
    )
    summary = {
        "schema_version": "policy-relative-deployment-feature-assembly-v1",
        "representation_ablation": "full-deployment-adapter-state",
        "label_source": "task-disjoint-crossfit-adapter-realized-advantage",
        "fold_summary_sha256": _sha256(fold_summary_path),
        "train": train_summary,
        "val": val_summary,
        "test_assets_read": False,
    }
    (output_root / "summary.json").write_text(
        json.dumps(summary, indent=2) + "\n", encoding="utf-8"
    )
    return summary


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("folds_root", type=Path)
    parser.add_argument("branch_root", type=Path)
    parser.add_argument("train_feature_root", type=Path)
    parser.add_argument("val_branch_root", type=Path)
    parser.add_argument("val_feature_root", type=Path)
    parser.add_argument("output_root", type=Path)
    args = parser.parse_args()
    result = assemble_deployment_features(
        args.folds_root,
        args.branch_root,
        args.train_feature_root,
        args.val_branch_root,
        args.val_feature_root,
        args.output_root,
    )
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
